name: 'GitHub Actions Access Manager'
description: 'Request a temporary access tokens to access or manage other repository resources.'
author: 'qoomon'
branding:
  icon: unlock
  color: blue
inputs:
  repo:
    description: 'The repository to request access token for. (e.g. example/test)'
    required: false
    default: 'self'
  endpoint:
    description: 'The app endpoint to request access token.'
    required: false
    default: 'https://github-actions-access-manager.vercel.app/'
outputs:
  token:
    description: 'The temporary repository access token'
runs:
  using: 'node16'
  main: 'dist/index.js'
